#ifndef _HEISEN_KERNEL_LIB_USB_CONFIG_H
#define _HEISEN_KERNEL_LIB_USB_CONFIG_H

#define DEFAULT_CONTROL_TIMEOUT_MILLIS 1000
#define DEFAULT_READ_TIMEOUT_MILLIS 200

#define READ_BUFFER_SIZE 256

#endif /*_HEISEN_KERNEL_LIB_USB_CONFIG_H*/