#ifndef __ALINIX_KERNEL_PBUF_HEADER_NET_INCLUDED_H
#define __ALINIX_KERNEL_PBUF_HEADER_NET_INCLUDED_H

typedef enum {
  PBUF_TRANSPORT,
  PBUF_IP,
  PBUF_LINK,
  PBUF_RAW
} pbuf_layer;

#endif	/* __ALINIX_KERNEL_PBUF_HEADER_NET_INCLUDED_H */